steps:
# Deploy container image to Cloud Run Services
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'inventory-system/spanner/'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE'
  - '--source'
  - '.'
  - '--region'
  - '$_REGION'
  - '--platform'
  - 'managed'
  - '--port'
  - '$_PORT'
  - '--update-env-vars'
  - 'SPANNER_CONNECTION_STRING=$_SPANNER_CONNECTION_STRING'