steps:
# Build the container image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'inventory-system/spanner/'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'inventory-system/spanner/'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA']

# Deploy container image to Cloud Run Services
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'inventory-system/spanner/'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA'
  - '--region'
  - '$_REGION'
  - '--platform'
  - 'managed'
  - '--port'
  - '$_PORT'
  - '--update-env-vars'
  - 'SPANNER_CONNECTION_STRING=$_SPANNER_CONNECTION_STRING'