# AI powered code reviews using Gemini CLI
name: Code Reviews
run-name: Reviewing ${{ github.actor }}'s code changes  🚀
on: [push, workflow_dispatch]
env:
  GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
jobs:
  Gemini-CLI-Code-Reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli
      # By setting working-directory, gemini will look inside menu-service
      - name: Documentation Coverage Review
        working-directory: ${{ github.workspace }}/menu-service
        run: |
          echo '## Documentation Coverage Review Results 🚀' >> $GITHUB_STEP_SUMMARY
          gemini -p 'Review Java code, check that all classes are properly documented, and provide suggestions on how to improve it. Return findings in markdown format.' >> $GITHUB_STEP_SUMMARY
      - name: Test Coverage Review
        working-directory: ${{ github.workspace }}/menu-service
        run: |
          echo '## Test Coverage Review Results 🚀' >> $GITHUB_STEP_SUMMARY
          gemini -p 'Review Java code, check that all classes and methods have test coverage, and provide suggestions on how to improve it. Return findings in markdown format.' -y >> $GITHUB_STEP_SUMMARY
