# AI powered code reviews using Gemini CLI
name: Code Reviews
run-name: Reviewing ${{ github.actor }}'s code changes  🚀
#on: [push, workflow_dispatch]
on: []
env:
  GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
jobs:
  Gemini-CLI-Code-Reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: cd ${{ github.workspace }}/menu-service
      - run: npm install -g @google/gemini-cli

      - name: Documentation Coverage Review
        run: echo '## Documentation Coverage Review Results 🚀' >> $GITHUB_STEP_SUMMARY
      - run: gemini -p 'review menu-service java code and check that all classes are properly documented and provide suggestions on how to improve the documentation in the code and return findings as text in markdown format to the console' >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Test Coverage Review
        run: echo '## Test Coverage Review Results 🚀' >> $GITHUB_STEP_SUMMARY
      - run: gemini -p 'review menu-service java code and check that all classes and methods have test coverage and provide suggestions on how to improve the test coverage in the code and return findings as text in markdown format to the console' -y >> $GITHUB_STEP_SUMMARY
        shell: bash
